### ISSUE TITLE
Admin unable to flag user as administrator, advertiser, and/or publisher

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#1007]
# Bug Report

## Describe the bug

As an admin, I cannot update an existing user's account to set them as both an advertiser and publisher.

## Expected behavior

On the user edit for (admin only), I would like to see three checkboxes:

- [ ] Administrator
- [ ] Advertiser
- [ ] Publisher

And when I update the form, it will update the user

## Steps To Reproduce

Go to any publisher and try to make them an advertiser

**Comment by andrewmcodes** [comment]
This is not an issue.
