### ISSUE TITLE
Campaign list under user is not correct

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#1010]
# Bug Report

## Describe the bug

As an admin, when I view a user's account and click on the 'Campaigns' tab under them, I only see the campaigns that are for my active team and not those that belong to the teams this user belongs to.

## Expected behavior

I should see a list of campaigns that this user has access to (their teams campaigns)

## Steps To Reproduce

As an admin, go to any user that is an advertiser with active campaigns and then click on the tab "campaigns"

### Screenshots

<img width="1510" alt="CodeFund___Ethical_Advertising_-_Firefox_Developer_Edition" src="https://user-images.githubusercontent.com/12481/72455824-bb8ad180-3780-11ea-879d-fd9aa5ee2062.png">

### Desktop
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Firefox

**Comment by coderberry** [comment]
It's working. Nothing to fix

**Comment by andrewmcodes** [comment]
This was closed on accident - should have been #1007
