### ISSUE TITLE
Campaign form helper buttons for audience targeting

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#1018]
# Feature Request

## What problem does this solve

We are migrating to Audiences for targeting, but having the keywords is still nice. However it's hard to know exactly which keywords fall under each audience when filling out the campaign form.

## Describe the solution you'd like

I would like to see clickable badges (like the ALL and CLEAR) that will populate the Targeted Keywords field with all of the keywords that are associated with the audience I click.

## Describe alternatives you've considered

Do it by hand

## Additional context

<img width="1469" alt="CodeFund___Ethical_Advertising_-_Firefox_Developer_Edition" src="https://user-images.githubusercontent.com/12481/72544939-6e246800-3845-11ea-8bd8-e3b2ad0a209b.png">

**Comment by andrewmcodes** [comment]
Relies on #1021

**Comment by andrewmcodes** [comment]
All you need to do is choose the audience and these will be automatically selected.
