### ISSUE TITLE
Add "BackYourStack" to the products panel

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#1050]
# Feature Request

## What problem does this solve

We are now partners with BackYourStack.com. We want to support this partnership.

## Describe the solution you'd like

Replace CodeFund in the products panel with "BYS" and have it link to https://backyourstack.com/?utm_source=codefund. Update the logo and move this app to the bottom right slot.

See screenshot.

## Additional context

<img width="582" alt="CodeFund___Ethical_Advertising_-_Firefox_Developer_Edition" src="https://user-images.githubusercontent.com/12481/73079700-e1e7f580-3e81-11ea-8789-7f329dc6aed2.png">

**Comment by andrewmcodes** [comment]
Waiting for #1083
