### ISSUE TITLE
Publisher date filter presets do not update as days pass

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#1058]
Today, if I choose "This Month", I will get a filter for Jan 1 - 26. Tomorrow, if I load the dashboard again without touching the date filters...

Expected behaviour: filter is set to Jan 1 - 27.

Current behaviour: filter is set to Jan 1 - 26; I have to pick "This Month" again to get it to update.

**Comment by coderberry** [comment]
+1 - will prioritize
