### ISSUE TITLE
Publisher date filter should not have "Next Month" option

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#1062]
Because the future has not occurred yet.

**Comment by hopsoft** [comment]
This is only true for non time travelers. 😜

**Comment by andrewmcodes** [comment]
I took a look into this and I’m not sure if the trade off of work required and breakaway from our date picker pattern is worth it at this time. I’ll add this to my personal backlog but I’m going to close this for now. 

Thank you for the feedback! We appreciate it 😁
