### ISSUE TITLE
Add 'Solidity' as a keyword that belongs to the 'Blockchain' audience

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#1073]
# Feature Request

## What problem does this solve

This will help us determine which properties focus on development vs general audience within Blockchain.

## Describe the solution you'd like

Add 'Solidity' as a keyword that belongs to the 'Blockchain' audience

## Describe alternatives you've considered

N/A

## Additional context

Requested by publisher

**Comment by andrewmcodes** [comment]
Included in #1021
