### ISSUE TITLE
ads.txt entry for CodeFund

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#1181]
[AdSense is suggesting publishers add an ads.txt file.](https://support.google.com/adsense/answer/7532444)

What values, if any, should CodeFund publishers include in this file?

**Comment by andrewmcodes** [comment]
@JasonBarnabe I did some digging and I am not quite sure if you _really_ need this file, but the CodeFund entry should be:

```
# Ads.txt
# <ExchangeDomain>,<SellerAccountId>,<PaymentType>

# CodeFund
codefund.io, 1, DIRECT
```

Where `1` should be replaced with your user id. Comments aren't necessary, and I didn't want to use your real user id but I believe this is what you need. To get your user id, simply log in to the app, and go to your user profile, and grab the id from the url (Ex: `https://app.codefund.io/users/736`) 

Lmk if your understanding is different and I'll happily continue researching this.

Also worth mentioning that `ads.txt` should be in your `robots.txt` file and should also be a visitable route from the application ([Example](https://www.miamiherald.com/ads.txt))

**Comment by andrewmcodes** [comment]
If you're satisfied with this answer let me know and we will add it to our wiki!

**Comment by JasonBarnabe** [comment]
Yeah, not sure if it's _really_ needed, but when Google tells you to do something...

I've added that, thanks.

**Comment by andrewmcodes** [comment]
@JasonBarnabe I realized I had a typo above. 

`Ensure crawling is not disallowed by robots.txt` via [Google's documentation](https://support.google.com/adsense/answer/7679060?hl=en)

**Comment by andrewmcodes** [comment]
[Entry added to the wiki](https://github.com/gitcoinco/code_fund_ads/wiki/Ads.txt) until we can find a better place to surface documentation like this. Thanks @JasonBarnabe
