### ISSUE TITLE
Property dashboard "Fill rate (past 24 hours)" is not showing me 24 hours of data

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#1183]
https://app.codefund.io/properties/230

![Screenshot_2020-03-26 CodeFund Ethical Advertising](https://user-images.githubusercontent.com/583995/77714300-aadbb080-6fa6-11ea-9f5e-4ceb7738b0d0.png)

This seems to be doing "since midnight UTC" rather than "past 24 hours".

**Comment by andrewmcodes** [comment]
@hopsoft can you check `question 418`?

**Comment by hopsoft** [comment]
Thanks. I'll be reviewing this later today.

**Comment by hopsoft** [comment]
This should be all fixed up.
