### ISSUE TITLE
CodeFund JS event sometimes fires twice

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#1196]
I use an event listener so that when CodeFund has no paid ad, I put in another ad network in its place. My code is [here](https://github.com/JasonBarnabe/greasyfork/blob/master/app/assets/javascripts/ads.js).

I noticed that sometimes the event fires twice. This is messing up my ad swapping (though I can fix that easily enough).

The page serving the ad is [here](https://greasyfork.org/en/scripts/375583-killermod-all-in-one-the-best-moomoo-io-mod-hack-spike-trap-hotkey-autobull-autoheal-and-more). When the problem happens, you can see this in the console:

```
CodeFund does not have an advertiser for you at this time.
codefund event: [object Object]
CodeFund container element not visible! Please verify an element exists (and is visible) that matches the CSS selector "#codefund_ad"
codefund event: [object Object]
```

(Followed by some errors caused by my assumption this would only run once.)

This problem does not occur on every page load. I'm testing with Firefox.

**Comment by JasonBarnabe** [comment]
This also happens when there is a paid ad available - in this case my page would just log `codefund event: [object Object]` twice.

**Comment by andrewmcodes** [comment]
@JasonBarnabe did you do something on your end to prevent this from happening? I haven't been able to reproduce

**Comment by JasonBarnabe** [comment]
Haven't changed anything. Tried just now, reproduced 4 times out of 10.

**Comment by andrewmcodes** [comment]
@coderberry if you get a chance can you take a look at this?

**Comment by coderberry** [comment]
@JasonBarnabe I was unable to replicate this.. however I did add the callback logging in our /demo landing page with this PR. This will allow us all to test this on a public page, but will also serve as an example implementation as well.
