### ISSUE TITLE
Don't load CSS file when theme = unstyled

### ISSUE THREAD

**Issue by Booligoosh** [gitcoinco/code_fund_ads#1228]
# Feature Request

## What problem does this solve

I use unstyled CodeFund ads for performance reasons. However, it still loads the CSS file even when the theme is unstyled. 0% of the CSS in the file is used.

![Screen Shot 2020-04-21 at 5 50 30 pm](https://user-images.githubusercontent.com/14034891/79840220-fbed9180-83f8-11ea-84cc-b016c4a921cd.png)

## Describe the solution you'd like

Remove the stylesheet link from the HTML when the theme is `unstyled`

## Describe alternatives you've considered

For the moment, I've removed the stylesheet from the HTML manually with a regular expression before adding to the DOM:
```javascript
fetch("https://api.codefund.app/properties/xx/funder.html?$third-party")
  .then(r => r.text())
  .then(
    html =>
      (document.getElementById("codefund").innerHTML = html
        /* Remove stylesheet link to save network usage */
        .replace(/<link .*?rel="stylesheet".*?>/g, ""))
  )
  .catch(
    () =>
      (document.getElementById("codefund").innerHTML =
        '<div class="codefund-placeholder" style="text-align: left">Please consider disabling your ad blocker to support this site.<br><br>This rectangle is the only place on the page where ads are shown.</div>')
  );
```

## Additional context

I am using the `funder.html` way of doing things rather than `funder.js` (again for performance reasons).

**Comment by andrewmcodes** [comment]
Good catch @Booligoosh, I will see what we can do

**Comment by andrewmcodes** [comment]
@coderberry can you look into this?
