### ISSUE TITLE
Audience-based targeting is bleeding into other audiences

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#1280]
# Bug Report

## Describe the bug

There are properties that belong to audiences outside of the campaign's targeting appearing in the 'Properties' tab and have been displaying ads for them.

## Expected behavior

A property should not show an ad for an advertiser where the property's audience is not included in the campaign's targeting.

## Steps To Reproduce

Go to campaign 844 and review the property list

**Comment by andrewmcodes** [comment]
@coderberry I believe we looked into this and at one point the properties were actually targeting this campaign.
