### ISSUE TITLE
Country emoji does not appear for Windows users on country lists

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#1281]
# Bug Report

## Describe the bug

The campaign country list displays the emoji with the flag for the country it represents, but doesn't appear property on Windows.

## Expected behavior

The flag should appear property (or be removed)

## Steps To Reproduce

1. Use windows
2. Go to any campaign's country report
3. Find that the emoji's are missing

### Screenshots

![Image 2020-05-14 at 9 52 14 AM](https://user-images.githubusercontent.com/12481/81956543-ae63df00-95c8-11ea-820d-1bd50ce9ffe5.png)

**Comment by andrewmcodes** [comment]
@coderberry is there a console error? What browser are you using? Do you see this locally?
