### ISSUE TITLE
Country targeting bleeds into other countries

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#1283]
# Bug Report

## Describe the bug

Ads are displayed in other countries (and no country) even though the targeting of a campaign is strictly US and Canada.

## Expected behavior

Only show ads in US and Canada when those are the only regions selected.

## Steps To Reproduce

1. Review campaign #837

### Screenshots

![Image 2020-05-14 at 10 32 35 AM](https://user-images.githubusercontent.com/12481/81960529-5203be00-95ce-11ea-8766-244b533edd6a.png)

**Comment by andrewmcodes** [comment]
It seems this is no longer an issue after #1275. Will continue to monitor.
