### ISSUE TITLE
Update minimum traffic field on Publisher page

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#252]
Super awesome feedback from a super awesome applicant:

> It's possible my site does get at least 5,000 visitors per month. The number that I'm able to see is under-counting because many of the visitors use a browser extension that blocks reporting to Google Analytics on the client-side. I've just requested that my hosting provider expose their server-side analytics so I can know the exact number, but they haven't yet done so.

> The form on https://codefund.io/publishers allows submitting even with the visitors dropdown set to the default value of "less than 5,000 per month". So I expected the response to still include some useful follow-up.

> If there is no useful follow-up at this time, I suggest changing the form UI to disallow submission and highlight the minimum if someone tries to submit it with less than 5,000 visitors per month selected.

> How about also changing your email to include something like "We'll let you know if our minimum ever changes, and if your website starts to meet the current minimum in the meantime, please submit again!"

**Comment by filips123** [comment]
Why is there a traffic limit? Many new sites don't have much traffic so they can't have ads.

**Comment by coderberry** [comment]
@filips123 The reason we have a minimum is that we have a minimum payout of $20 for distributions. When a publisher is added to CodeFund with less than 5,000 impressions per month, it will take many months to accrue the minimum distribution amount.

In the future we hope to decrease the minimum to zero by introducing crypto-based distributions.

**Comment by filips123** [comment]
Yes, but even if it takes many months to get $20, it is still better for publishers that they are not accepted.

And crypto-based distributions would be great! When will this be?

**Comment by coderberry** [comment]
> Yes, but even if it takes many months to get $20, it is still better for publishers then they are not accepted.

I agree. This was the idea behind the original Code Sponsor product we launched last year. Until our distributions and onboarding become automated, we need to hold off from opening the doors to everyone.

> And crypto-based distributions would be great! When will this be?

We already do this with some publishers, but it's not an automated thing yet. Scale is something we will likely look at in Q2. This would definitely fall under scale.

**Comment by justJS** [comment]
Just gonna jump in here - I was recently accepted as I'm pretty sure I'll hit the minimum, but I've had feedback from friends that, for example, they'd like to add CodeFund and are still working on getting to 5000 unique visitors, or that they have over 5000 unique visitors per month, but on different sites of theirs.

I do understand the minimum payout for now but as said above it'd be awesome to allow more people to join CodeFund 🙂

**Comment by hopsoft** [comment]
One idea might be to let low volume publishers join and integrate, but keep the low traffic sites in a `pending` state (only showing fallback ads) until they reach the minimum traffic volume for payouts.

**Comment by hopsoft** [comment]
We are going to remove the friction to publisher signup and integration. The minimum requirement will only impact whether or not their property is activated for premium ads.

**Comment by filips123** [comment]
@hopsoft Does this mean that I can also register a website with less than 5000 visitors? Also, it there any update regarding crypto-based distributions?

**Comment by hopsoft** [comment]
Yes. We are going to open the doors for any publisher to register and integrate. However, publisher sites will still need to be approved prior to being turned *active* to receive paid ads.

Cypto-based distributions is on the road map by we likely won't get there until 3rd or 4th quarter next year.
