### ISSUE TITLE
javascript escaping bug in ad text

### ISSUE THREAD

**Issue by aaronpk** [gitcoinco/code_fund_ads#264]
Here's a snapshot of the JS returned for my site: https://gist.github.com/aaronpk/d1c6a5e86e9b7e91f275f1e84a0b8dca

There is a syntax error because a single quote in the ad text is not being escaped:

```
targetElement.innerHTML = '<div id="cf"> ... Take Triplebyte's multiple-choice ... </div>';
```

**Comment by coderberry** [comment]
@hopsoft It looks like we need to revisit the escaping of the ad text

**Comment by hopsoft** [comment]
Will look into this first thing today.
