### ISSUE TITLE
CodeFund Jobs: Preview link points to a dead link

### ISSUE THREAD

**Issue by arku** [gitcoinco/code_fund_ads#296]
### Steps to reproduce

1. Go to the [new job listing page](https://codefund.app/jobs/listings/new)
2. Submit the form by clicking on 'Next' without filling in anything
3. Now, click on 'Preview' at the top

You should get be taken to https://codefund.app/jobs/listings but the page doesn't exist. It should instead be on https://codefund.app/jobs/listings/new

**Comment by hopsoft** [comment]
Putting this in icebox until we revisit the job board.
