### ISSUE TITLE
Publisher Success Audit

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#309]
Go through each property on CodeFund and verify the following:

* Logged in?
* Embedded Code?
* Profile Updated?
* 5,000 Impressions?
* Acceptable Ad?
* Paid?

Follow up with all properties to ask feedback on how we can improve or help them succeed better.

https://www.notion.so/gitcoin/bba7f9f4025d4fc8b579610726f33e98?v=a07329c3d64f45fbbbb3792b55073413

**Comment by hopsoft** [comment]
Created a report to help with this (its slow, but has some good info). https://metabase.codefund.io/question/98
