### ISSUE TITLE
Some ads are not being displayed

### ISSUE THREAD

**Issue by julianschiavo** [gitcoinco/code_fund_ads#320]
## Description
Due to some ads using font names such as `'Helvetica Neue'` (note the quotes) they aren't being displayed, because in the `funder.js`, it's causing the `innerHTML` attribute to close:

```'<div id="cf"> <span class="cf-wrapper" style="z-index: 1; font-family: system, 'Helvetica Neue'```

As seen above, the start quote (before the div) is closed by the single quote used for the font name (Helvetica Neue).

Note that this only happens in certain ads which use font names that contain spaces.

## Solution
If single quotes are used, they should be escaped when put into the JavaScript.

## Related
Also reported on the Gitcoin Slack.

**Working ad VS broken ad diff: https://www.diffchecker.com/cvziIu6u**

**Comment by hopsoft** [comment]
Do you know specifically what template + theme combo you were using when you first noticed this?

I've tested with several of the template/theme combos with single quoted css values like `font-family: system, 'Helvetica Neue', Helvetica, Arial;` but have been unable to reproduce the reported behavior.

**Comment by hopsoft** [comment]
Tested combos that pass manual checks.

- `bottom-bar/dark`
- `bottom-bar/light`
- `horizontal/light`
- `horizontal/dark`

**Comment by hopsoft** [comment]
What device + browser combo was used when this behavior was observed?

**Comment by justJS** [comment]
Hotizontal Light. One of the advertisers it seems to happen with is **ZingGrid** if that helps @hopsoft

**Comment by justJS** [comment]
Hey, I was just able to reproduce it and this time it happened on a **Rollbar** ad. (ID: 123)

**Comment by hopsoft** [comment]
Issue #347 may be related.

**Comment by hopsoft** [comment]
We are going to be reworking our ad templates soon which should eradicate these types of problems.
