### ISSUE TITLE
API call for HTML is broken

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#347]
As an example, go to https://api.codefund.app/properties/184/funder.html

**Comment by hopsoft** [comment]
I'm am seeing this behavior in production, but haven't been able to replicate locally... even with a fresh backup of production data. I wonder what's different between environments. I'm going to try running in "production" mode locally.

**Comment by hopsoft** [comment]
Unable to reproduce locally via localhost or running through ngrok... even when running in `production` mode with a fresh prod dataset. My current theory is that either Heroku is munging the rendered HTML or that a proxy is... perhaps the ISP? 🤷‍♂️

**Comment by coderberry** [comment]
Fixed
