### ISSUE TITLE
Property not properly displaying on events screen

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#391]
As a publisher, the events views I see on URLs like https://codefund.app/properties/XXXXX/events does not properly show my property beside each event. Instead I see entries like this:

```
Jason Barnabe
#<Property:0x00007f8876b2b960>
Property was created
about 1 hour ago
```

**Comment by coderberry** [comment]
@JasonBarnabe This is great feedback. We will add it to our list of items to do. As you know we are also open source. If you want to submit a PR with this change that would be great!

**Comment by andrewmcodes** [comment]
@hopsoft this seems to be working correctly now and should be safe to close.
