### ISSUE TITLE
Publishers are not told what the properties being in "Pending" status means

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#392]
As a publisher who just signed up, I see a yellow circle on the dashboard beside by property's name. Hovering over the yellow circle, I see the tooltip "Pending". However there is no indication what "Pending" means, or what (if anything) I need to do to stop being "Pending".

**Comment by coderberry** [comment]
@JasonBarnabe Thanks for this feedback. You are correct in that we need to make this more user-friendly. Just so you know, "Pending" means that it is awaiting approval from myself.

We have in our queue a task to set up notifiers when new properties are added. Hopefully that will minimize time as "pending".
