### ISSUE TITLE
"(why allow fallback ads?)" has no tooltip when page is navigated to

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#393]
As a publisher, when I navigate to edit my property, the tooltip for "(why allow fallback ads?)"  does not work. If I visit https://codefund.app/properties/XXXXX/edit directly, it does.

**Comment by coderberry** [comment]
Hi @JasonBarnabe, thanks for submitting this. It's a known issue with our implementation of the bootstrap popover library and Turbolinks.

@hopsoft can you please take this one?

**Comment by andrewmcodes** [comment]
@hopsoft this seems to be working correctly now and should be safe to close.
