### ISSUE TITLE
Preview for template and theme options

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#398]
As a publisher, I would like to see a preview of the template and theme options from my property edit screen so I don't have to repeated save then go to my site or Instructions to see what each means.

**Comment by coderberry** [comment]
@JasonBarnabe This is a great idea. I'll add it to our task list.

**Comment by hopsoft** [comment]
This should probably be implemented as a new route. Something like `property_previews`

This can be implemented in a similar way to creative previews. See: https://github.com/gitcoinco/code_fund_ads/blob/master/config/routes.rb#L100-L104

**Comment by arp242** [comment]
Even some simple description would already be a massive improvement. Right now I have 13 options and absolutely zero idea what any of them do. It's [not even documented in the source](https://github.com/gitcoinco/code_fund_ads/tree/master/app/views/ad_templates) as far as I can find.

**Comment by andrewmcodes** [comment]
We are in the process of creating a solution for this.

**Comment by andrewmcodes** [comment]
This should be solved by visiting https://app.codefund.io/demo. If not, please let me know!
