### ISSUE TITLE
"Jobs" in publisher menu doesn't make sense

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#399]
As a publisher, the menu on my publisher dashboard shows: Dashboard, Properties, Jobs, Profile. "Jobs" doesn't seem to have anything to do with me as a publisher and should be removed to avoid confusion. It can remain in the top-level menu (Home, Advertisers, Publishers, Pricing, Jobs, Blog).

**Comment by coderberry** [comment]
Hi @JasonBarnabe .. this is great feedback. We will consider this change.

**Comment by coderberry** [comment]
We have removed Jobs from all navigation.
