### ISSUE TITLE
Fallback ads under campaigns should be labeled as such

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#413]
As a publisher, I would like an indication of which campaigns in the campaigns list are fallback ads that do not generate revenue for me. This would help me to understand the fill rate and the performance of non-fallback ads.

**Comment by hopsoft** [comment]
Putting in icebox until we revisit the campaigns list.

**Comment by JasonBarnabe** [comment]
This appears to have been accomplished in the new design.
