### ISSUE TITLE
Campaigns list should allow publishers to see the ad

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#414]
As a publisher, I would like to see what the ads for the campaigns on my campaigns list look like. Some of the names are very obtuse ("Do you qualify?") and I am a curious publisher.

**Comment by hopsoft** [comment]
Great feature request. I'm going to put in the icebox for now until we bring back the campaigns list.

**Comment by andrewmcodes** [comment]
@JasonBarnabe Are you wanting to see the actual content of the ad or just the layout? If it's the former, you can see the ad layouts [here](https://app.codefund.io/demo).

**Comment by JasonBarnabe** [comment]
@andrewmcodes Just the layout. That demo page is good. It should be incorporated into the settings page somehow (a link at minimum).

**Comment by andrewmcodes** [comment]
We can make that happen 😄 thanks @JasonBarnabe!
