### ISSUE TITLE
Posted jobs do not appear in users list

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#422]
If I post a job as an existing advertiser, I cannot see the job in the job list within the admin

![image](https://user-images.githubusercontent.com/12481/54638754-62afb700-4a51-11e9-952e-ee4ab8998853.png)

**Comment by rymcmahon** [comment]
Hi! While looking to contribute I came across this bug but it looks resolved? When I go to `/jobs/manage` locally I see a job I created. Or is there another location/route?

<img width="1214" alt="Screen Shot 2019-09-14 at 6 30 42 AM" src="https://user-images.githubusercontent.com/8561395/64906854-45366f80-d6b9-11e9-87dd-363f2d6bb520.png">
