### ISSUE TITLE
New invitee is unable to log in

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#427]
## User Story

As a {type of user}, I want {some goal} so that {some reason}.

## Description

What is it all about?

## Acceptance Critera

What is the expected solution?

## Related

List any URL's or other issues that provide more context.

**Comment by andrewmcodes** [comment]
I have tested this and cannot replicate the behavior. If we cannot get more information on the error, maybe we should close this until it pops up again. @hopsoft

**Comment by hopsoft** [comment]
Sounds good.
