### ISSUE TITLE
Publisher menu is excessive on mobile

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#453]
![Screen Shot 2019-03-29 at 14 40 56](https://user-images.githubusercontent.com/583995/55258420-ccd61200-5230-11e9-8a0f-ac0531fa9fd9.png)

The publisher menu on mobile is excessive. It's ~800px high, which is more than a screenful.

**Comment by hopsoft** [comment]
The skin and redesign will resolve this. Keep an eye peeled for activity around this.
