### ISSUE TITLE
Creatives are missing data (by date)

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#486]
See screenshot:

<img width="375" alt="Screenshot_5_3_19__11_42_AM" src="https://user-images.githubusercontent.com/12481/57155392-909a5200-6d98-11e9-8c44-fcb41c7624bb.png">

**Comment by hopsoft** [comment]
We need to wait for #581 to land before we populate with numbers. I'll temporarily remove the numbers on this view for now until that PR ships and we backfill the rollup data.
