### ISSUE TITLE
Troubles with development environment installation

### ISSUE THREAD

**Issue by JeremiGendron** [gitcoinco/code_fund_ads#535]
## User Story

As a contributing developer, I want an easy environment setup so that I can be more productive.

## Description

What is it all about?
The README.md doesn't provide enough information for a smooth installation experience.

## Acceptance Critera

What is the expected solution?
Update the README.md to reflect more information about how the environment should be installed, which components are required, correct versions for every component, and a few pointers.

## Related

#534

**Comment by hopsoft** [comment]
This should be resolved with #633
