### ISSUE TITLE
Suggestion: Enable CircleCI builds on forked pull requests

### ISSUE THREAD

**Issue by mglaman** [gitcoinco/code_fund_ads#551]
## User Story

As a contributor, I want to see CircleCI test results on my pull request so that I know I didn't bork the system.

## Description

By default, CircleCI does not build forked pull requests. Only pull requests which originate on as branch on the same repository.

![Screen Shot 2019-06-19 at 5 08 10 PM](https://user-images.githubusercontent.com/3698644/59874822-d325e700-9364-11e9-8b29-2c11bcf09047.png)

## Acceptance Critera

Contributors can open pull requests and see if they broke the build.

**Comment by andrewmcodes** [comment]
We have enabled this setting to build forked pull requests 🎉
