### ISSUE TITLE
Select advertiser from dropdown on campaign form is broken

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#558]
## User Story

As an admin, I click to clone a campaign, then choose a new advertiser. Once I do this, the available creatives shows an error.

<img width="2362" alt="CodeFund___Campaigns" src="https://user-images.githubusercontent.com/12481/60202262-6cdb1180-9807-11e9-91d9-4a8326deae9d.png">

**Comment by hopsoft** [comment]
Likely related to #550
