### ISSUE TITLE
Yesterday's earnings stats are set to zero

### ISSUE THREAD

**Issue by idoshamun** [gitcoinco/code_fund_ads#587]
## User Story

As a publisher, I want to see yesterday's earning stats.

## Description

Every day, yesterday's earning stats are broken until noon (Israel time). Then they go back to normal and show the real information.
This is very odd because if I look at today's stats they look perfect and when today becomes yesterday they are set to zero.

## Acceptance Critera

Yesterday's stats should be ok during the whole day.

**Comment by hopsoft** [comment]
I'll take a stab at explaining what's happening technically. _This isn't a solution only a description of what's causing the observed behavior._

- We store all data in UTC and reports are also based on UTC
- We have a background task that rolls up daily data that kicks off at 9:00 AM UTC
- Our reporting dashboard shows **historical data** from our rollups OLAP and **current day** activity from our "transactions" OLTP

**Comment by hopsoft** [comment]
This is also causing overspend for high traffic sites. /cc @coderberry

**Comment by andrewmcodes** [comment]
@hopsoft is this still an issue?

**Comment by idoshamun** [comment]
I think that it is already fixed :)

**Comment by andrewmcodes** [comment]
Awesome!
