### ISSUE TITLE
Faker deprecations and some breaking changes

### ISSUE THREAD

**Issue by dahal** [gitcoinco/code_fund_ads#608]
## User Story

Faker gem has deprecated some APIs. Looks like they have also changed namespaces and classes resulting on some deprecation messages and errors while running initial seed.

### 1. Breaking Changes
`Faker::SiliconValley` has moved to => `Faker::TvShows::SiliconValley`
* https://github.com/faker-ruby/faker/blob/master/doc/tv_shows/silicon_valley.md

<img width="1050" alt="Screen Shot 2019-09-10 at 7 27 31 PM" src="https://user-images.githubusercontent.com/3684236/64663676-6f5e0800-d401-11e9-9825-b87b2f6caca2.png">

### 1. Deprecation warnings

```ruby
code_fund_ads/db/seeds.rb:284: Passing `name` with the 1st argument of `Internet.email` 
is deprecated. Use keyword argument like `Internet.email(name: ...)` 
instead
```

## Related

* https://github.com/faker-ruby/faker/issues/1576

**Comment by andrewmcodes** [comment]
This should be resolved now that #633 has been merged.
