### ISSUE TITLE
Godot Game Engine intergration

### ISSUE THREAD

**Issue by Burnsedia** [gitcoinco/code_fund_ads#628]
## User Story

As a Game Developer with Godot Game engine, I want CodeFund ads for games so that so that I am not spying on the users of my AGPL game.

## Description
godot 3.1 + intergration either though c/c++(GDnative Scripts) or C++ core modual and or GDscript plugin

## Acceptance Critera

easy to use, like the Firebase plugin.

## Related

List any URL's or other issues that provide more context.

**Comment by coderberry** [comment]
@Burnsedia Thank you for submitting this. I'm sorry it's taken this long to get back to you. I love the Godot Game engine, however, this integration really doesn't make sense at this time. Our network focuses on software developers, and the audience for games is everyone. We wouldn't be able to provide advertising for this reason.

**Comment by Burnsedia** [comment]
I am making a game that teaches you to use the Unix/Linux terminal and use
NoSql and SQL based DataBases using SQLite and either Redis or MongoDB

**Comment by Burnsedia** [comment]
Using Godot for the easy Web Assimbly
