### ISSUE TITLE
Clone Creatives as an advertiser

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#663]
As an advertiser, I want to clone creatives. The button was there, then I removed it (not sure why).

<img width="1224" alt="CodeFund___Creatives" src="https://user-images.githubusercontent.com/12481/66528938-914fc500-eb3c-11e9-8fd3-445e69a36b98.png">

**Comment by andrewmcodes** [comment]
@coderberry 
![image](https://user-images.githubusercontent.com/18423853/66591961-17323700-eb62-11e9-909a-a63fe1a0c74e.png)

The reason this you cannot clone in this specific case is because the creative is locked bc it is active.
