### ISSUE TITLE
SameSite warning in Chrome

### ISSUE THREAD

**Issue by andrewmcodes** [gitcoinco/code_fund_ads#671]
## Description

>I recently noticed this warning in Chrome's console (I don't use Chrome as my main browser). This shows when I visit www.bootstrapcdn.com

```
(index):1 A cookie associated with a cross-site resource at https://codefund.io/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
17:04:29.830 (index):1 A cookie associated with a cross-site resource at http://codefund.app/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

## Acceptance Critera

This error will no longer be shown and we will add `SameSite=Secure/None`.

**Comment by andrewmcodes** [comment]
@coderberry: @hopsoft was able to completely remove the cookies from the browser, but we do initially create one and then delete it. This is a rails thing that we cannot get around, and rails does not currently support setting `SameSite` (see [rails#28297](https://github.com/rails/rails/pull/28297)). 

When Rails does support this, we can set something so this warning no longer pops up, but I think we could go ahead and close this considering the cookie now gets removed entirely whereas it just expired after the session did previously. Let me know if I can say more.

![image](https://user-images.githubusercontent.com/18423853/68345575-a5e19780-00bf-11ea-9fe7-eeafccd6c503.png)

**Comment by coderberry** [comment]
@andrewmcodes I love this!

**Comment by andrewmcodes** [comment]
Actually now this shouldn't show up a warning at all! :tada:
