### ISSUE TITLE
Ensure all S3 images are routed through codefund.io, not codefund.app

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#696]
## Description

Some browsers and ad blockers are blocking the images when they are shown from cdnx.codefund.app. We should ensure we use the codefund.io domain

Test criteria:

Using the Brave browser, go to https://codefund.io/campaigns/475 and verify the images are appearing

**Comment by andrewmcodes** [comment]
@hopsoft will need your guidance here. I believe the reasoning for this is the bucket name in s3 but I could be wrong.

**Comment by cmckee-dev** [comment]
@andrewmcodes If you have aws credentials I can pair with you on this. Its some Route53 configuration.

**Comment by andrewmcodes** [comment]
@hopsoft bump

**Comment by hopsoft** [comment]
The fix for this is related to configurations in Cloudflare DNS and AWS CloudFront. I'm looking into what needs to be added/changed in each system as this was original setup by @coderberry

**Comment by hopsoft** [comment]
Configs have been updated. This should be working now.
