### ISSUE TITLE
Unable to create new campaign from clone

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#697]
## User Story

As an administrator, I can clone a campaign and save it with changes.

## Description

There is an issue with the javascript on the campaign form. When I submit a cloned campaign and just change the date and creatives, I get the following error:

![image](https://user-images.githubusercontent.com/12481/67233677-f3dc7700-f400-11e9-9060-d15d075fb26a.png)

**Comment by andrewmcodes** [comment]
@coderberry let's talk about this - I have not been able to recreate this issue.
