### ISSUE TITLE
Alert team when publisher impressions have a dramatic drop

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#734]
## User Story

As an admin, we need to know when publishers remove the ads or reduce the inventory.

**Comment by andrewmcodes** [comment]
@coderberry is this something we want in the UI, or emails, or even slack messages? What are you thinking?

**Comment by andrewmcodes** [comment]
From Justin:

- Slack/Email notification
- Property has gone from having impressions and then they don't (below 5 impressions per day)
- 24 hour timeframe until message
- Only for active properties.
