### ISSUE TITLE
Develop new ad templates that use JS

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#735]
## User Story

As a publisher, I want to select an ad template that will only display when the the visitor scrolls down. It drops down from the top (with a close button)

## Description

There are a handful of new templates we should explore. Here's some examples written by @octavioamu 

[codefund_templates.zip](https://github.com/gitcoinco/code_fund_ads/files/3772805/codefund_templates.zip)

**Comment by hopsoft** [comment]
These are great. Thank you @octavioamu ❤️
