### ISSUE TITLE
Replace "nofollow" with "sponsored" in the ad templates

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#756]
Google has recently announced a change in its policy for rel="nofollow" and outbound links. Moz blog post helps navigate the changes.

We need to replace "nofollow" with "sponsored" in the ad templates.

**Comment by logichub** [comment]
I found following instances of `nofoolow`:
1. `app/views/ad_templates/*`  => 14
2. `app/views/campaigns/*` => 01
3. `app/views_redesigned/campaigns/*` => 01
4. `test/system/*` => 01
5. `vendor/themes/*` => 20

Would you like to change all such instances or only those falling under `app/views/ad_templates/*` path?
