### ISSUE TITLE
Property cards on publisher dashboard should have a minimum width

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#800]
https://app.codefund.io/dashboards/publisher

With 5 properties, the wrapping is getting a little silly.

![Screenshot_2019-11-11 Publisher Dashboards](https://user-images.githubusercontent.com/583995/68637771-49b6b300-04c5-11ea-87aa-1ff318a566b2.png)

**Comment by andrewmcodes** [comment]
@JasonBarnabe This will be fixed with the redesign work we are currently engaged on. Thanks for letting us know this is bothersome! 😄
