### ISSUE TITLE
"Estimated Traffic" is way off for unused property

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#810]
https://app.codefund.io/properties?date_range=11%2F01%2F2019+-+11%2F14%2F2019

Property 233 shows:

![Screenshot_2019-11-14 Properties](https://user-images.githubusercontent.com/583995/68914807-5df8eb00-0725-11ea-96a8-62ddcfe3f81d.png)

But this property only has a trickle of traffic, as shown on https://app.codefund.io/properties/233/earnings?date_range=11%2F01%2F2019+-+11%2F14%2F2019

![Screenshot_2019-11-14 Property Earnings](https://user-images.githubusercontent.com/583995/68914835-7832c900-0725-11ea-9911-6d0087657c8b.png)

**Comment by andrewmcodes** [comment]
Weird. Thanks for letting us know @JasonBarnabe. I’ll fix this up first thing in the morning!

**Comment by andrewmcodes** [comment]
@JasonBarnabe wanted to update you that we actually use a service to generate these numbers which would explain why they look off. We are still deciding about what to do about this.

**Comment by andrewmcodes** [comment]
This will be removed when the new site design is launched.
