### ISSUE TITLE
Box fallback when there are no Japanese fonts

### ISSUE THREAD

**Issue by arp242** [gitcoinco/code_fund_ads#816]
My property is listed with a Unicode fallback character:

![screenshot_2019-11-15-23-15-45](https://user-images.githubusercontent.com/1032692/68953966-f95d8f00-07fd-11ea-96d5-3305b5b1c676.png)

Turns out this is a Japanese character:

```
$ uni i ・
     cpoint  dec    utf-8       html       name
'・' U+30FB  12539  e3 83 bb    &#x30fb;   KATAKANA MIDDLE DOT (Other_Punctuation)
```

Probably better to use the more standard U+00B7 MIDDLE DOT? Most people with Latin fonts will have that.

### Desktop
 - OS: Linux
 - Browser: Firefox 70.0

**Comment by hopsoft** [comment]
Great catch. Thank you for the report. @andrewmcodes this is most likely due to this method and others like it. https://github.com/gitcoinco/code_fund_ads/blob/master/app/models/concerns/properties/presentable.rb#L6

**Comment by andrewmcodes** [comment]
@arp242 You should be seeing the correct character now, let us know if you aren't! 

![image](https://user-images.githubusercontent.com/18423853/68969952-284f1300-07b4-11ea-8e20-cd20fa554056.png)

**Comment by arp242** [comment]
Did this get deployed? As far as I can see nothing changed. I reloaded the page with browser cache disabled.

**Comment by andrewmcodes** [comment]
@arp242 i apologize I thought we did because I couldn’t reproduce it anymore. I’ll get that fixed up today. Sorry about that!

**Comment by arp242** [comment]
No hurries; it's a small visual issue. Everything works just fine.

**Comment by andrewmcodes** [comment]
@arp242 this will get deployed today or Monday. Thanks for letting us know!
