### ISSUE TITLE
Unclear what "fallback ads" are

### ISSUE THREAD

**Issue by arp242** [gitcoinco/code_fund_ads#817]
The text for "fallback ads" is, IMHO, rather unclear:

![screenshot_2019-11-15-23-12-20](https://user-images.githubusercontent.com/1032692/68954375-db445e80-07fe-11ea-8732-77442dd3ce99.png)

It took a bit of very careful reading and experimentation to discover that fallback ads are displayed when there are no campaigns from advertisers that fit the site, so it displays ads for Codefund or OpenCollective. At least, I think that's what they are?

It's still unclear to me if these "fallback ads" give revenue (probably not)? It's also unclear what *exactly* gets displayed. What are "community messages" for example?

It would be helpful if the help text could be expanded and/or link to a page with more extensive details.

**Comment by andrewmcodes** [comment]
@arp242 

>It's still unclear to me if these "fallback ads" give revenue (probably not)?

Correct, they do not.

>What are "community messages"

Basically there are a few advertisers, including CodeFund, that will display an ad. You are correct that this text isn't super clear and we will be updating it as part of our redesign effort.

I have extracted this text from our [FAQ](https://codefund.io/faq), let me know if you have any more questions!

>From time to time, our advertisers have us remove websites from their targeting due to poor performance. When this happens, more fallback ads appear, driving the CPM down. This is no reflection on the value that publishers provide to their communities. It’s more so the value that the advertisers derive from their ads on their site. Publishers can turn off fallback ads at any time.

**Comment by arp242** [comment]
Note the FAQ is only linked in the footer on codefund.io, and *not* app.codefund.io when you're logged in.

**Comment by andrewmcodes** [comment]
@arp242 correct. We will have it in the footer when the new site design is launched very soon.
