### ISSUE TITLE
Allow S3/Cloudfront for localhost

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#821]
Our S3/Cloudfront returns 403 unauthorized for ad images when we request from localhost. It would be great if we could loose up those rules to allow public access. Here's an example:

```
➜  curl -v https://d3a2el5l1ud3kv.cloudfront.net/WLwssevv5fCaDAmN2HM6ods7
*   Trying 13.33.252.159:443...
* TCP_NODELAY set
* Connected to d3a2el5l1ud3kv.cloudfront.net (13.33.252.159) port 443 (#0)
* ALPN, offering http/1.1
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.cloudfront.net
* Server certificate: DigiCert Global CA G2
* Server certificate: DigiCert Global Root G2
> GET /WLwssevv5fCaDAmN2HM6ods7 HTTP/1.1
> Host: d3a2el5l1ud3kv.cloudfront.net
> User-Agent: curl/7.67.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< Date: Tue, 19 Nov 2019 17:10:06 GMT
< Server: AmazonS3
< X-Cache: Error from cloudfront
< Via: 1.1 db88a4a8e4f93b9bfeab5462f253c306.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: DEN50-C1
< X-Amz-Cf-Id: 2v7R7zS03wqucdf3Bzji3v1W5Io5XjjzBBAHRuPpwqwCcTL7dQwSJw==
<
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host d3a2el5l1ud3kv.cloudfront.net left intact
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>4D42B1914FCFA845</RequestId><HostId>dScRsTyrBa3D91pvuWShF4H5TFJcQAbHWO2vfPzu5YWLMV5KK7IqcZqMTMGx2lI7heLjImhD2EY=</HostId></Error>%
```

**Comment by andrewmcodes** [comment]
You just need to update your `storage.yml` file to pull from S3 and not localhost. The reason we changed this is bc contributors without the the proper credentials will have issues with this. 

In my mind we should do the following:

Create a `storage.yml.example` and add the real `storage.yml` to the .gitignore so you can specify your own settings. I did this in the Docker PR with the database config file. Then we just need to update our procfile to `cp config/storage.yml.example config/storage.yml` or use a binstub similar to the one I added in the Docker PR

**Comment by hopsoft** [comment]
Actually I think this is related to S3/Cloudfront permission settings.

**Comment by andrewmcodes** [comment]
This was due to a misconfigured environment variable.
