### ISSUE TITLE
Enhance Property Earnings Report

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#831]
# Feature Request

## What problem does this solve

Publishers are confused why the same impressions are driving less money at times. Here's an example:

![image](https://user-images.githubusercontent.com/12481/69548723-165c3580-0f55-11ea-9750-f94f978036f8.png)

## Describe the solution you'd like

We need to update these columns to have more informative data. Here's what we should have:

- [ ] Paid Impressions
- [ ] Paid Clicks
- [ ] Paid CTR
- [ ] Fallback Impressions
- [ ] Fallback Clicks
- [ ] Fallback CTR
- [ ] Earnings

## Describe alternatives you've considered

Metabase

## Additional context

N/A

**Comment by andrewmcodes** [comment]
This has been added.
