### ISSUE TITLE
Application errors in publisher area

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#843]
Getting lots of "Application Error"s in the publisher area lately. Generally this is in the lazily loaded stats sections and will resolve itself after reloading.

**Comment by JasonBarnabe** [comment]
![Screenshot_2019-11-28 Publisher Dashboards](https://user-images.githubusercontent.com/583995/69822007-ce464880-11ca-11ea-9a05-ac6e427a5951.png)

**Comment by andrewmcodes** [comment]
@JasonBarnabe sorry about this. Looking into it and will get it fixed ASAP.

**Comment by hopsoft** [comment]
We need to audit the publisher dashboard queries. I expect that it queries the `impressions` tables rather than `daily_summaries`. If so, this is a long overdue optimization that's been neglected.

**Comment by andrewmcodes** [comment]
@JasonBarnabe are you still seeing this with the new skin?

**Comment by JasonBarnabe** [comment]
I have yet to see this problem with the new design.
