### ISSUE TITLE
CSS and JS are not compressed

### ISSUE THREAD

**Issue by arp242** [gitcoinco/code_fund_ads#869]
My sites loads:

- https://app.codefund.io/packs/css/code_fund_ad-671bae33.css
- https://app.codefund.io/packs/js/code_fund_ad-d1ab71f2b6e935ef47c6.js

These files are served uncompressed; a lot of data could be saved just by compressing these files:

```
[~/codefund]% ls -lh
total 88K
-rw-r--r-- 1 martin martin  38K Dec  5 02:04 css
-rw-r--r-- 1 martin martin 3.9K Dec  5 02:04 css.gz
-rw-r--r-- 1 martin martin  33K Dec  5 02:05 js
-rw-r--r-- 1 martin martin 7.9K Dec  5 02:05 js.gz
```

Note the average page size is about ~25k for me, so adding 71k for CodeFund is quite an increase! I know that it's "normal" to have a news article loads 3M of data (larger than my entire site), but a lot of tech people are not especially happy with that, and try to minimize this footprint (living in Indonesia with a sub-optimal connection means I definitely notice the issues as described in e.g. [this][1] and [this][2]) I think it makes sense to spend some time optimizing this, and this seems like a good first step!

[1]: https://timkadlec.com/remembers/2019-01-09-the-ethics-of-performance/
[2]: http://danluu.com/web-bloat/

**Comment by hopsoft** [comment]
🤔 This is most likely something we missed in the nginx config since the compressed variants are pre-generated and could/should be served when the `Accept-Encoding: gzip, deflate, br` is present. https://github.com/gitcoinco/code_fund_ads/blob/master/config/nginx.conf.erb

**Comment by andrewmcodes** [comment]
@hopsoft bump

**Comment by andrewmcodes** [comment]
@arp242 are you still seeing this? I investigated a bit today and chrome said they were minified and I was not getting the same file sizes but perhaps I am missing something? Thanks 😄

**Comment by arp242** [comment]
Yeah, they're "minified" @andrewmcodes, but not compressed with gzip:

![screenshot_2020-02-12-03-56-01_border](https://user-images.githubusercontent.com/1032692/74273570-a8e9c500-4d4b-11ea-94b1-8088074224d5.png)

I'd expect it to have a `Content-Encoding: gzip` so the filesizes are roughly similar to the above example.

**Comment by andrewmcodes** [comment]
ah gotcha - thanks! I'll see if we can get this taken care of.

**Comment by andrewmcodes** [comment]
This is proving way harder than we thought. Working on soliciting help from someone more knowledgeable on the subject bc my various attempts have not succeeded 😣

**Comment by arp242** [comment]
Thanks Andrew! I don't mind doing legwork for this.

I looked at your [nginx.conf](https://github.com/gitcoinco/code_fund_ads/blob/69aab78f1f5a4a85cc47f26987c697b485f5fbf1/config/nginx.conf.erb), it looks like you added `gzip_static on`, which means it'll try to load `file.js.gz` from the filesystem if it exists, falling back to the uncompressed `file.js` if it doesn't. If I test this locally with your nginx.conf (or rather, a simpler version of it) that seems to work as expected.

In the lice server, the `Cache-Control: public` and `Expires: <far future> are added, so it seems the condition is matches properly, but that the `.gz` files don't exist? It's really hard to confirm from the outside though :sweat_smile: 

Maybe you just want `gzip on`?

**Comment by andrewmcodes** [comment]
@arp242 So it may be worth noting that whenever we deploy to production, a task is run that actually creates gzipped actions, which is provided from the webpacker gem. We followed [their suggestions](https://github.com/rails/webpacker/blob/master/docs/deployment.md#nginx) for using Nginx, which obviously isn't quite right.

I will certainly give your suggestion a test run and see if that solves it! One thing someone else told me is that the reason we may be having issues is bc we are using Nginx as a proxy and sent me [this link](https://reinout.vanrees.org/weblog/2015/11/19/nginx-proxy-gzip.html).

I am sure there is another way to do it, and we could use Cloudflare but were hoping to just use Nginx. I will give your suggestion a shot and let you know what happens! Thanks!

**Comment by arp242** [comment]
Right; like I mentioned, that server block *seems* to be applied as indicated by the other headers, so I *think* that either something else is removing the compression (Heroku [shouldn't do this though](https://devcenter.heroku.com/articles/compressing-http-messages-with-gzip)), or there's something wrong with that task and the files aren't created correct.

By trying `gzip on` you can at least narrow down the problem a bit: if that works, then it's a problem with the rake task, if it still doesn't work, then it's something else.

**Comment by andrewmcodes** [comment]
@arp242 wanted to update you that we finally found the right concoction of settings to get gzip working. Initial tests are showing about a 70% size reduction 🎉 We want to do a little more testing but we should have this rolled out first thing Monday. Thanks for your help in tracking down the issue!

**Comment by andrewmcodes** [comment]
This has been deployed - let us know if you see any issues @arp242. Thanks again!

**Comment by arp242** [comment]
Cheers, seems to work as expected :+1:
