### ISSUE TITLE
Don't show screenshots on publisher dashboard

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#895]
As a publisher who has a bunch of properties, I want a screen where I can see at a glance how all my properties are doing.

The newly designed publisher dashboard has cards for each property, and these cards contain screenshots of the my website. I know what my site looks like, so the screenshot is really not very useful to me here. It makes it so I can't see all properties in one screenful. So I would suggest removing the screenshots from this view.

**Comment by andrewmcodes** [comment]
@JasonBarnabe I will talk to the team but your situation is a bit unique. Most publishers have several different properties that are different sites, whereas your properties all point to the same one.

**Comment by coderberry** [comment]
Hi @JasonBarnabe that's great feedback. I agree with you and also think that others would appreciate a more compact, data-rich view as well. I'll mock something up for us to replace it with.

**Comment by coderberry** [comment]
@andrewmcodes 
![image](https://user-images.githubusercontent.com/12481/70669397-82b48580-1c33-11ea-8578-a275370bbe12.png)

**Comment by andrewmcodes** [comment]
Just need the metabase dashboard and then I can take care of this.

**Comment by coderberry** [comment]
@andrewmcodes https://metabase.codefund.io/dashboard/14
