### ISSUE TITLE
Cards on publisher dashboard are wildly different sizes

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#896]
On the new publisher dashboard, I have 7 properties. At a laptop screen width of ~1300px, 3 of them fit in a row. The first 6 are the same size, then the 7th also fills the row, so is triple size. They should all be the same size.

**Comment by andrewmcodes** [comment]
This is a bootstrap thing. I’m planning to use CSS Grid here, which will fix this issue.
