### ISSUE TITLE
Property overview stats/graphs are not displayed in an efficient way

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#897]
In Firefox on a laptop screen ~1300px wide, the cards in the publisher are one per row, and the height seems fixed. So I have 600x400 boxes, some of which with a single number and word in them.
![Screenshot_2019-12-10 Properties](https://user-images.githubusercontent.com/583995/70581399-bb455800-1b7c-11ea-8893-493156b77abf.png)

**Comment by andrewmcodes** [comment]
@JasonBarnabe Just make your window a bit smaller. We cannot control the metabase responsiveness but if you make your window a bit smaller, the sidebar will be hidden by default and the overview will have more room to expand.
