### ISSUE TITLE
Paid ad rate is not worthy of a graph

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#898]
![Screenshot_2019-12-10 Properties(1)](https://user-images.githubusercontent.com/583995/70581794-09a72680-1b7e-11ea-85de-933705ef2f43.png)

This tachometer graph is not adding anything to the 95% number. Drop the graph, just show the number.

**Comment by coderberry** [comment]
@JasonBarnabe let's pair in our dashboard builder and we can work out a good dashboard together.  DM me

**Comment by coderberry** [comment]
Closed by accident

**Comment by andrewmcodes** [comment]
Assigning to you @coderberry. Let me know when you have something for me to do for this.

**Comment by coderberry** [comment]
Agreed. This chart has been removed.
