### ISSUE TITLE
Property stat numbers look like links, but do nothing

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#900]
Property overview stats show a hand on hover, but clicking them does nothing.

**Comment by andrewmcodes** [comment]
Good catch, thank you @JasonBarnabe. Will fix in the morning.

**Comment by andrewmcodes** [comment]
This is actually how our 3rd party service, Metabase, displays these. We do not have an ability to turn the hover off or disable the cursor pointer.
