### ISSUE TITLE
Links on publisher property campaigns page lead to 404

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#915]
e.g. https://app.codefund.io/properties/230/campaigns links to https://app.codefund.io/campaigns/465, which is a 404 (at least for me).

**Comment by coderberry** [comment]
@JasonBarnabe you are amazing!

**Comment by andrewmcodes** [comment]
🙏 Fixed and we will get this shipped out in the morning. Thank you @JasonBarnabe
