### ISSUE TITLE
Property summary CTR and CPM are unclear if they're paid or paid and fallback

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#926]
On the property screen, there's a Summary section on the right. This includes CPM and CTR stats.

- CPM (based on the numbers I'm seeing) appears to be (revenue) / (1000 _paid_ impressions), which is  misleading. I think per total (paid + fallback) impressions would be a more valid stat. But at least it should better indicate what it is.
- CTR - not sure if this is just paid or paid + fallback.

**Comment by coderberry** [comment]
@JasonBarnabe We have decided to report both paid and fallback stats separately. This is what our competitors do and it better reflects the pricing that the publisher is receiving.

All stats displayed in the summary section is for paid traffic only.
