### ISSUE TITLE
Last n days is a better default stat than month to date

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#929]
As a publisher, I like to log in to look at my stats and see how things are going. "Month to date" stats are not particularly useful - they just get bigger and bigger and then reset to 0. Defaulting to "Last 7 days" would be better.

AdSense looks like it defaults to last 7 days, but also shows "Today so far", "Yesterday", "Last 7 days", and "This month" revenue stats on its dashboard.

**Comment by andrewmcodes** [comment]
@JasonBarnabe if this will help I’ll make the change. Reasoning makes sense, thank you for your detailed report.

**Comment by coderberry** [comment]
I believe this should be a user configuration. The MTD is what most of our users look to. If we do this, it should be built into user preferences and not globally applied.

**Comment by JasonBarnabe** [comment]
@coderberry Do most _publishers_ want MTD? I could see how advertisers with a monthly budget would...

**Comment by coderberry** [comment]
@JasonBarnabe That is correct

**Comment by andrewmcodes** [comment]
Closing for now.
