### ISSUE TITLE
Changes/diff modal and created/updated at

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#932]
The modal that shows when you click "x made changes" on the property dashboard...

- Always shows "created at" with "No Changes".
- Always shows "updated at" as changed.

Neither of these should show.

**Comment by coderberry** [comment]
Hi @JasonBarnabe this is a great enhancement request. The same issue has bothered me for a long time. I am going to set this issue as a low priority, but open to contributions.
