### ISSUE TITLE
Property changelog could have a more useful summary

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#933]
In the changelog section of the property dashboard, instead of showing "Justin Dorfman made changes", it would be more useful to say what changed, like "Just Dorfman changed status to 'Active' (and 3 other changes)."

**Comment by andrewmcodes** [comment]
@JasonBarnabe The changelog should stack events on top of each other as they come in. Here is an example:

![image](https://user-images.githubusercontent.com/18423853/70935092-689ced80-200d-11ea-9bf4-9e843ea15bc1.png)

**Comment by coderberry** [comment]
@JasonBarnabe I agree with your request. The library we are using doesn't provide a lot of details in this summary view. I also wanted to keep the text short so it would fit well in the sidebar.

Perhaps in the future we can enhance this section.
