### ISSUE TITLE
Property changelog diffs have weird version numbers

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#935]
The diffs of things in the changelog show version numbers that jump around all over the place. Should probably show a date instead of a version number I have no control over and doesn't make sense to me.

**Comment by andrewmcodes** [comment]
@JasonBarnabe this is a global id in the system. What benefit would seeing the date have for your workflow?

**Comment by JasonBarnabe** [comment]
The date is not that useful, but the version number is confusing. Just suggesting date as something to replace it.

**Comment by coderberry** [comment]
We actually use that version number for internal reference. Let's leave it as is for now.
