### ISSUE TITLE
Unable to create campaign

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#942]
# Bug Report

## Describe the bug

I am unable to create a new campaign due to a validation error

## Expected behavior

I should be able to save a new campaign

## Steps To Reproduce

1. Log in as admin
2. Go to https://app.codefund.io/campaigns/new?clone=333
3. Ensure at least one creative is selected
3. Click `Save`
4. See error `Creative must exist`

### Screenshots

![image](https://user-images.githubusercontent.com/12481/71011691-18746880-20ab-11ea-89b3-e3bb68c71bf5.png)

**Comment by andrewmcodes** [comment]
This was fixed and released.
