### ISSUE TITLE
Enhance the creative list view for campaigns

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#944]
# Feature Request

## What problem does this solve

It allows advertisers to see which creatives are active and what they look like without navigating away.

## Describe the solution you'd like

On the campaign > creative table list, show an indicator to the left (maybe a checkmark or circle) that shows that the creative is still active for that campaign. Also have a preview button (icon) that displays the ad preview (square template) in a popover or modal.

## Describe alternatives you've considered

This is an advertiser request.

## Additional context

<img width="873" alt="CodeFund___Ethical_Advertising" src="https://user-images.githubusercontent.com/12481/71040727-838e6100-20e4-11ea-8e49-5e58658ef1bb.png">

**Comment by andrewmcodes** [comment]
@coderberry would you mind creating a simple wireframe for this?
