### ISSUE TITLE
Discourse CodeFund plugin is throwing an error

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#946]
# Bug Report

## Describe the bug

Ads are not appearing on Discourse due to an error.

## Expected behavior

Ads should appear properly.

## Steps To Reproduce

1. Go to https://www.ruby-forum.com/
2. View browser console / network console
3. Review errors

### Screenshots

![image](https://user-images.githubusercontent.com/12481/71100122-ad419980-2171-11ea-8c16-fc0d54fca4da.png)

**Comment by hopsoft** [comment]
Note that the server responds with a `404` and the following JSON body.

```
{"message":"CodeFund does not have an advertiser for you at this time."}
```

This is a legitimate response from the server, but we need to update the Discourse plugin to handle the scenario when an ad isn't available. Another thing we should track down is why this property isn't getting fallback ads when premium ads run out.

**Comment by andrewmcodes** [comment]
We fixed the problem with the fallbacks.
