### ISSUE TITLE
Add role definitions in invite/add member to org screen

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#953]
# Feature Request

## What problem does this solve

The roles do not really make any sense for organization administrators inviting users.

## Describe the solution you'd like

I would like to see a section above the form that describes the roles.

## Additional context

<img width="1236" alt="CodeFund___Ethical_Advertising" src="https://user-images.githubusercontent.com/12481/71198406-ed2b7e00-2250-11ea-906e-a58df43e7663.png">

**Comment by andrewmcodes** [comment]
Holding off on this until images are updated.
