### ISSUE TITLE
Alternate payment methods

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#960]
PayPal takes ~3.5% of payments as fees. This can be a substantial amount. Wire transfers cost ~$50. Once a publisher reaches a certain level, they should have the option to provide wire transfer details and receive payments that way.

**Comment by coderberry** [comment]
@JasonBarnabe we also do payouts using TransferWise which does have much lower fees. Please let us know if that's what you'd like to use.
