### ISSUE TITLE
Campaign flag not working

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#984]
# Bug Report

## Describe the bug

I can't update the flag "Restrict premium campaigns to those that have explicitly assigned this property"

## Expected behavior

It should work

## Steps To Reproduce

Go to any property and try to enable it (make sure you disable after)

### Screenshots

<img width="843" alt="CodeFund___Ethical_Advertising" src="https://user-images.githubusercontent.com/12481/72022547-f5fae880-322d-11ea-8216-f0428535db4b.png">

**Comment by andrewmcodes** [comment]
fixed by #986
