### ISSUE TITLE
Remove all 3rd party tracking for our websites

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#989]
Right now we are using Google Analytics on our marketing site and our app. I would like us to follow the example of DHH and only have internal tracking.

This is not something that will happen soon, but I'd like to work this into Q2.

Blog post: https://m.signalvnoise.com/the-last-tracker-was-just-removed-from-basecamp-com/

**Comment by andrewmcodes** [comment]
Curious if we use any of the analytic data for the app? I imagine we don't now that we have the Wordpress site so I personally would argue for just removing it entirely.
