### ISSUE TITLE
Improve Teams Index for Admins

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#990]
# Feature Request

## What problem does this solve

The current layout of the teams index page does not provide much data and is hard to follow without a header row.

## Describe the solution you'd like

I would like to see the following columns:

* Balance (remaining balance)
* Paid (sum of credit transactions that are not gifted)
* Gifted (sum of credit transactions that are gifted)
* Active Campaigns (number, link to org campaigns overview)
* Total Campaigns (number, link to org campaigns overview)
* Team Members (number, link to org members page)
* End Date (end date of most recent campaign)
* Last Login (date of most recent login of members)

There should be a summary row (footer or below header).

I would also like the data to be segmented into three categories:

* Active (only show teams that have active campaigns)
* Inactive (only show teams that do not have active campaigns)
* All

## Additional context

![image](https://user-images.githubusercontent.com/12481/72086152-b2eb5480-32c3-11ea-943b-05d951c775d9.png)

## Extra Credit

It would be ideal to use [Kendo Grid](https://www.telerik.com/kendo-ui/grid) for this view. They provide column-based filtering which would solve a lot of issues not only for this table but for others as well.

**Comment by andrewmcodes** [comment]
I have plenty of ideas of where to go with this but I’m holding off until we figure out if we’ll be using Kendo’s grid product or not.
